Repository hugegraph/hugegraph, pull requests merged in 2025-09, with the labels that each got.

#27 refactor(store): integrate store grpc module
  hugegraph-store/hg-store-grpc/src/main/proto/graphpb.proto
  hugegraph-store/hg-store-grpc/src/main/proto/query.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_common.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_session.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_state.proto
  hugegraph-store/hg-store-grpc/src/main/proto/store_stream_meta.proto
Labels: enhancement, size:L

#22 feat(pd): add methods to query graph status and cluster status
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/PDClient.java
  hugegraph-pd/hg-pd-grpc/src/main/proto/pdpb.proto
  hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/rest/MemberAPI.java
  hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/service/PDService.java
Labels: enhancement, size:L, lgtm

#34 refactor(store): integrate store rocksDb module
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBFactory.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBOptions.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBScanIterator.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBSession.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/SessionOperatorImpl.java
Labels: size:L, lgtm

#48 refactor(store): integrate store cli module
  hugegraph-store/hg-store-cli/pom.xml
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/CliApplication.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/StoreConsoleApplication.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/Load.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/MultiQuery.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/Scan.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/ScanShard.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/ScanSingleShard.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/cmd/ScanTable.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/loader/HgThread2DB.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/scan/HgStoreCommitter.java
  hugegraph-store/hg-store-cli/src/main/java/org/apache/hugegraph/store/cli/scan/HgStoreScanner.java
Labels: enhancement, size:XXL, lgtm

#51 fix problems found in ci
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/PartitionInstructionProcessor.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/business/itrv2/IntersectionFilterIterator.java
  hugegraph-store/hg-store-core/src/main/java/org/apache/hugegraph/store/pd/DefaultPdProvider.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/AppConfig.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/EmptyIterator.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/GrpcClosure.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreNodeService.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/HgStoreSessionImpl.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/grpc/query/MultiKeyComparator.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/metrics/ProcfsMetrics.java
  hugegraph-store/hg-store-node/src/main/java/org/apache/hugegraph/store/node/metrics/SystemMemoryStats.java
  hugegraph-store/hg-store-rocksdb/src/main/java/org/apache/hugegraph/rocksdb/access/RocksDBSession.java
  hugegraph-store/hg-store-test/src/main/java/org/apache/hugegraph/store/core/store/HgStoreEngineTest.java
  hugegraph-struct/src/main/java/org/apache/hugegraph/serializer/BinaryElementSerializer.java
Labels: bug, size:L, lgtm

#54 fix(test): fix pd ci test
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/AbstractClient.java
  hugegraph-pd/hg-pd-client/src/main/java/org/apache/hugegraph/pd/client/ClientCache.java
  hugegraph-pd/hg-pd-service/src/main/java/org/apache/hugegraph/pd/rest/PromTargetsAPI.java
  hugegraph-pd/hg-pd-test/src/main/java/org/apache/hugegraph/pd/BaseTest.java
  hugegraph-pd/hg-pd-test/src/main/java/org/apache/hugegraph/pd/core/PDCoreSuiteTest.java
  hugegraph-pd/hg-pd-test/src/main/java/org/apache/hugegraph/pd/rest/RestApiTest.java
Labels: bug, size:L, lgtm
